<script lang="ts">
	import SEOHead from '$lib/components/SEOHead.svelte';
</script>

<SEOHead
	title="Terms of Service"
	description="Terms and conditions for using Gordie, the AI fantasy sports assistant."
	canonical="/terms"
	noindex={true}
/>

<article class="legal-page">
	<div class="container legal-container">
		<h1>Terms of Service</h1>
		<p class="last-updated">Last updated: February 5, 2025</p>

		<section>
			<h2>Agreement</h2>
			<p>By using Gordie ("the Service"), operated by Lasting Software ("we", "us", "our"), you agree to these terms. If you don't agree, please don't use the Service.</p>
		</section>

		<section>
			<h2>What Gordie Is</h2>
			<p>Gordie is an AI-powered fantasy sports assistant that provides advice, analysis, and recommendations via email. Gordie is a tool to help inform your decisions — it does not guarantee results and should not be treated as a substitute for your own judgment.</p>
		</section>

		<section>
			<h2>The Service</h2>
			<ul>
				<li>Gordie is currently in <strong>beta</strong> and is provided free of charge. We may introduce pricing in the future with advance notice.</li>
				<li>We may modify, suspend, or discontinue the Service at any time.</li>
				<li>Gordie accesses your Yahoo Fantasy data with <strong>read-only permissions</strong>. Gordie will never make roster changes, accept trades, or drop players on your behalf.</li>
			</ul>
		</section>

		<section>
			<h2>Your Account</h2>
			<ul>
				<li>You must provide a valid email address to use Gordie.</li>
				<li>You are responsible for maintaining access to your email account.</li>
				<li>You agree not to use the Service for any unlawful purpose or to abuse, harass, or spam the Service.</li>
			</ul>
		</section>

		<section>
			<h2>AI-Generated Content</h2>
			<p>Gordie's responses are generated by artificial intelligence. While we strive for accuracy:</p>
			<ul>
				<li>Advice may contain errors or inaccuracies.</li>
				<li>Statistics and projections are based on available data and may not reflect real-time changes.</li>
				<li>Gordie's recommendations are not financial advice, gambling advice, or guaranteed outcomes.</li>
				<li>You are solely responsible for any roster decisions you make based on Gordie's advice.</li>
			</ul>
		</section>

		<section>
			<h2>Acceptable Use</h2>
			<p>You agree not to:</p>
			<ul>
				<li>Attempt to reverse engineer, extract, or scrape the Service.</li>
				<li>Use automated tools to send excessive requests to the Service.</li>
				<li>Resell, redistribute, or commercially exploit Gordie's output without our permission.</li>
				<li>Use the Service to generate content that is harmful, misleading, or illegal.</li>
			</ul>
		</section>

		<section>
			<h2>Intellectual Property</h2>
			<p>The Service, including its design, code, and branding, is owned by Lasting Software. Content generated by Gordie in response to your queries is provided for your personal use.</p>
		</section>

		<section>
			<h2>Limitation of Liability</h2>
			<p>The Service is provided "as is" without warranties of any kind. To the fullest extent permitted by law, Lasting Software is not liable for any indirect, incidental, or consequential damages arising from your use of the Service, including but not limited to losses in fantasy sports competitions.</p>
		</section>

		<section>
			<h2>Termination</h2>
			<p>We may suspend or terminate your access to the Service at our discretion if you violate these terms. You may stop using the Service at any time by emailing <a href="mailto:support@lastingsoftware.ca">support@lastingsoftware.ca</a> to request account deletion.</p>
		</section>

		<section>
			<h2>Changes to These Terms</h2>
			<p>We may update these terms from time to time. If we make significant changes, we'll notify you by email. Continued use of the Service after changes constitutes acceptance of the updated terms.</p>
		</section>

		<section>
			<h2>Contact</h2>
			<p>Questions about these terms? Email <a href="mailto:support@lastingsoftware.ca">support@lastingsoftware.ca</a>.</p>
		</section>
	</div>
</article>

<style>
	.legal-page {
		padding: 4rem 0;
	}

	.legal-container {
		max-width: 720px;
	}

	.legal-container h1 {
		font-family: var(--font-sans);
		text-transform: none;
		letter-spacing: normal;
		margin-bottom: 0.5rem;
	}

	.last-updated {
		color: var(--color-text-muted);
		font-size: 0.9rem;
		margin-bottom: 2.5rem;
	}

	section {
		margin-bottom: 2rem;
	}

	section h2 {
		font-family: var(--font-sans);
		text-transform: none;
		letter-spacing: normal;
		font-size: 1.35rem;
		margin-bottom: 0.75rem;
	}

	section p {
		color: var(--color-text-muted);
		margin-bottom: 0.75rem;
		line-height: 1.7;
	}

	section ul {
		color: var(--color-text-muted);
		padding-left: 1.5rem;
		margin-bottom: 0.75rem;
	}

	section li {
		margin-bottom: 0.5rem;
		line-height: 1.7;
	}
</style>
