"""initial schema

Revision ID: e254af7bde01
Revises:
Create Date: 2026-02-11 11:35:03.482841

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e254af7bde01'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_summaries',
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_topics', sa.Text(), nullable=True),
    sa.Column('players_mentioned', sa.Text(), nullable=True),
    sa.Column('decisions_made', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('thread_id')
    )
    op.create_index('idx_conversation_summaries_user_email', 'conversation_summaries', ['user_email'], unique=False)
    op.create_table('nhl_player_game_stats',
    sa.Column('nhl_api_player_id', sa.Integer(), nullable=False),
    sa.Column('nhl_api_game_id', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('plus_minus', sa.Integer(), nullable=True),
    sa.Column('pim', sa.Integer(), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('power_play_goals', sa.Integer(), nullable=True),
    sa.Column('sog', sa.Integer(), nullable=True),
    sa.Column('faceoff_winning_pctg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('toi', sa.String(), nullable=True),
    sa.Column('blocked_shots', sa.Integer(), nullable=True),
    sa.Column('shifts', sa.Integer(), nullable=True),
    sa.Column('giveaways', sa.Integer(), nullable=True),
    sa.Column('takeaways', sa.Integer(), nullable=True),
    sa.Column('corsi_for', sa.Integer(), nullable=True),
    sa.Column('fenwick_for', sa.Integer(), nullable=True),
    sa.Column('missed_shots', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('nhl_api_player_id', 'nhl_api_game_id')
    )
    op.create_table('notification_types',
    sa.Column('type_key', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('type_key')
    )
    op.create_table('oauth_nonces',
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('nonce', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_email')
    )
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('yahoo_leagues',
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('game_key', sa.String(), nullable=False),
    sa.Column('league_name', sa.String(), nullable=False),
    sa.Column('league_type', sa.String(), nullable=False),
    sa.Column('league_settings', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('league_id')
    )
    op.create_table('email_threads',
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index('idx_email_threads_thread_id', 'email_threads', ['thread_id'], unique=False)
    op.create_index('idx_email_threads_user_email', 'email_threads', ['user_email'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('notification_type', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['yahoo_leagues.league_id'], ),
    sa.ForeignKeyConstraint(['notification_type'], ['notification_types.type_key'], ),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('user_email', 'league_id', 'notification_type')
    )
    op.create_table('yahoo_tokens',
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('yahoo_email', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('token_time', sa.DateTime(), nullable=False),
    sa.Column('token_type', sa.String(), server_default='Bearer', nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('user_email')
    )
    op.create_table('yahoo_user_teams',
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['yahoo_leagues.league_id'], ),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('league_id', 'team_id', 'user_email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('yahoo_user_teams')
    op.drop_table('yahoo_tokens')
    op.drop_table('notification_preferences')
    op.drop_index('idx_email_threads_user_email', table_name='email_threads')
    op.drop_index('idx_email_threads_thread_id', table_name='email_threads')
    op.drop_table('email_threads')
    op.drop_table('yahoo_leagues')
    op.drop_table('users')
    op.drop_table('oauth_nonces')
    op.drop_table('notification_types')
    op.drop_table('nhl_player_game_stats')
    op.drop_index('idx_conversation_summaries_user_email', table_name='conversation_summaries')
    op.drop_table('conversation_summaries')
    # ### end Alembic commands ###
